### ISSUE TITLE
Syntax error in cmp.lua

### ISSUE THREAD

**Issue by alexjh** [DavidRambo/nvim#2]
Fantastic work, I'm switching to Neovim and using your dotfiles as a guide.

I noticed an issue in cmp.lua:

https://github.com/DavidRambo/nvim/blob/main/lua/plugins/cmp.lua#L31

`["<C-n"]` and `["<C-p"]` are missing the trailing `>`.

**Comment by DavidRambo** [comment]
Hey, thanks very much! I'm glad my setup is helpful. nvim-cmp must have ignored my botched keymapping and used the defaults (which are the same), because it's worked this whole time.
